site_name: Dynautomate
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - toc.integrate
nav:
  - Getting started: index.md
  - Keyword File: keyfile.md
  - Keyword: keyword.md
  - Cards: cards.md
  - Nodes: nodes.md
  - Transformation: transform.md
